In [9]:
import numpy as np
import gym
import random
# https://github.com/simoninithomas/Deep_reinforcement_learning_Course/blob/master/rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):Q%20learning/FrozenLake/Q%20Learning%20with%20FrozenLake.ipynb

In [4]:
env = gym.make("FrozenLake-v0")


In [6]:
action_size = env.action_space.n
state_size = env.observation_space.n
print(action_size)
print(state_size)

4
16


In [7]:
qtable = np.zeros((state_size, action_size))

In [8]:
# the hyperparameter

total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005   

In [13]:
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    for step in range(max_steps):
        
        exp_tradeoff = random.uniform(0, 1)
        
        # If greater than epsilon --> exploitation
        if exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()
        
        # take the action
        new_state, reward, done, info = env.step(action)
        
        # update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        qtable[state, action] += learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))


    

Score over time: 0.46226666666666666


In [14]:
print(qtable)


[[3.64061523e-01 1.06248956e-02 9.72171368e-02 1.07972752e-01]
 [1.68883706e-04 4.19109640e-03 1.91009831e-03 5.87408221e-02]
 [4.93442870e-02 4.76543149e-03 1.31460631e-03 4.53580137e-03]
 [2.59866893e-03 9.22197466e-04 1.10003852e-03 4.58291121e-03]
 [5.26587958e-01 7.49144966e-02 2.74324628e-03 6.61256483e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.19043246e-03 3.26594485e-05 1.44033397e-04 2.75383519e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.07884031e-03 1.20113599e-03 8.08149998e-02 5.26638178e-01]
 [6.65261752e-03 7.29483630e-01 9.67384237e-03 4.42258276e-03]
 [1.60015072e-01 1.60571760e-01 2.03443545e-03 7.93375969e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.90731159e-02 2.83480040e-02 5.71863469e-01 5.49218155e-02]
 [2.49759940e-01 9.55592052e-01 6.83021324e-01 2.98146939e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [15]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 45
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 27
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 40
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 20
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 75
